package main

import (
	"errors"
	"flag"
	"fmt"
	"go/build"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
)

// ///////////////////////////////////////////////
// Types
// ///////////////////////////////////////////////

// platform is one os/arch pair, written goos/goarch.
type platform struct {
	goos   string
	goarch string
}

// lintCoverage is every build the lint and vet rows read: each pair
// Taskfile.yml's LINT_PLATFORMS names, once with no build tags and once with
// each tag set LINT_TAGS names. release is RELEASE_TARGETS, which the pairs
// must cover.
type lintCoverage struct {
	platforms []platform
	// tagSets opens with the empty set. Each other set is one word, with
	// commas between its tags, as go's -tags flag takes it.
	tagSets []string
	release []platform
}

// ///////////////////////////////////////////////
// Variables
// ///////////////////////////////////////////////

// laxMarkers are the texts golangci-lint 2.13.2 reads as a generated file's
// mark under `generated: lax`, which .golangci.yml sets because the header
// cmd/generate writes is not the strict form. Any of them, lowercased, in a
// comment the package-clause parse collects takes the file out of every
// linter (pkg/result/processors/exclusion_generated_file_matcher.go).
var laxMarkers = []string{"code generated", "do not edit", "autogenerated file", "* generated by: swagger codegen "}

// ///////////////////////////////////////////////
// The row
// ///////////////////////////////////////////////

// packagesFindings holds the package set every Go row reads. vet, lint,
// deadcode, testpair and build load packages the way `go list ./...` does and
// print no count of their own, so the row prints that one count and fails
// when it is zero. It inherits the environment those rows do, a GOFLAGS from
// the shell or .env included, so the count is theirs.
//
// It also refuses the ways code leaves those rows while it still builds: a
// package of this module that a build in cover reaches and ./... does not
// match, which a directory starting with _ or named testdata makes; a tracked
// Go file under a directory starting with _; a tracked Go file no build in
// cover compiles, which a build constraint or a file name naming another
// platform or tag makes; a release pair cover does not read; a tracked Go
// file carrying a lax generated marker that generated, the files cmd/generate
// writes, does not name, since golangci-lint then skips the whole file; and
// an inline waiver no linter checks.
func packagesFindings(run commandRunner, goTool, root string, tracked []string, cover lintCoverage, generated []string) (rowResult, error) {
	listed, out, err := goList(run, goTool, nil, "list", "./...")
	if err != nil {
		return rowResult{}, err
	}
	noun := "packages"
	if len(listed) == 1 {
		noun = "package"
	}
	result := rowResult{summary: fmt.Sprintf("go list ./... matched %d %s, and the rows read %s", len(listed), noun, cover), relay: out.stderr}
	if len(listed) == 0 {
		result.findings = append(result.findings, "go list ./... matched no package, so vet, lint, deadcode, testpair and build check nothing")
	}
	if out.code != 0 {
		result.findings = append(result.findings, fmt.Sprintf("go list exited %d", out.code))
		return result, nil
	}
	hidden, relay, err := hiddenPackageFindings(run, goTool, cover)
	if err != nil {
		return rowResult{}, err
	}
	result.relay = append(result.relay, relay...)
	result.findings = append(result.findings, hidden...)
	compiled, err := coverageFindings(root, tracked, cover)
	if err != nil {
		return rowResult{}, err
	}
	result.findings = append(result.findings, compiled...)
	marked, err := laxMarkerFindings(root, tracked, generated)
	if err != nil {
		return rowResult{}, err
	}
	result.findings = append(result.findings, marked...)
	waived, err := goWaiverFindings(root, tracked)
	if err != nil {
		return rowResult{}, err
	}
	result.findings = append(result.findings, waived...)
	return result, nil
}

// goList runs go with env and args and returns the lines it printed, less
// blank ones.
func goList(run commandRunner, goTool string, env []string, args ...string) ([]string, output, error) {
	out, err := run(goTool, env, args...)
	if err != nil {
		return nil, output{}, fmt.Errorf("running %s: %w", goTool, err)
	}
	var lines []string
	for line := range strings.Lines(string(out.stdout)) {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			lines = append(lines, trimmed)
		}
	}
	return lines, out, nil
}

// hiddenPackageFindings lists, for every build in cover, the packages of this
// module that ./... reaches, tests included, without matching them itself.
// go list marks each as DepOnly. The builds differ because a build constraint
// can import a package on one platform alone, and every pair the rows read
// ships or runs somewhere. It returns the findings and what go printed on
// stderr for a build that failed.
func hiddenPackageFindings(run commandRunner, goTool string, cover lintCoverage) ([]string, []byte, error) {
	var order []string
	builds := map[string][]string{}
	var findings []string
	var relay []byte
	for _, pair := range cover.platforms {
		for _, tags := range cover.tagSets {
			label := buildLabel(pair, tags)
			env := []string{"GOOS=" + pair.goos, "GOARCH=" + pair.goarch}
			reached, out, err := goList(run, goTool, env, "list", "-deps", "-test", "-tags="+tags,
				"-f", "{{if and .Module .Module.Main .DepOnly (not .ForTest)}}{{.ImportPath}}{{end}}", "./...")
			if err != nil {
				return nil, nil, err
			}
			if out.code != 0 {
				relay = append(relay, out.stderr...)
				findings = append(findings, fmt.Sprintf("go list -deps for %s exited %d", label, out.code))
				continue
			}
			for _, pkg := range reached {
				if _, seen := builds[pkg]; !seen {
					order = append(order, pkg)
				}
				builds[pkg] = append(builds[pkg], label)
			}
		}
	}
	for _, pkg := range order {
		findings = append(findings, fmt.Sprintf("%s is a package of this module that the build or a test reaches for %s, and go list ./... does not match it, so vet, lint and test never read it. A directory whose name starts with _ or ., or one named testdata, does this. Move it",
			pkg, strings.Join(builds[pkg], ", ")))
	}
	return findings, relay, nil
}

// ///////////////////////////////////////////////
// Coverage
// ///////////////////////////////////////////////

// parseCoverage reads the packages row's flags: -platforms and -release, each
// os/arch pairs separated by spaces, and -tags, tag sets separated by spaces.
// Taskfile.yml passes LINT_PLATFORMS, RELEASE_TARGETS and LINT_TAGS.
func parseCoverage(args []string) (lintCoverage, []string, error) {
	flags := flag.NewFlagSet("packages", flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	platforms := flags.String("platforms", "", "the os/arch pairs lint and vet read")
	tags := flags.String("tags", "", "the build tag sets lint and vet read beside none")
	release := flags.String("release", "", "the os/arch pairs a release ships")
	if err := flags.Parse(args); err != nil {
		return lintCoverage{}, nil, err
	}
	var cover lintCoverage
	var err error
	if cover.platforms, err = parsePlatforms(*platforms); err != nil {
		return lintCoverage{}, nil, fmt.Errorf("-platforms: %w", err)
	}
	if len(cover.platforms) == 0 {
		return lintCoverage{}, nil, errors.New("-platforms names no os/arch pair")
	}
	if cover.release, err = parsePlatforms(*release); err != nil {
		return lintCoverage{}, nil, fmt.Errorf("-release: %w", err)
	}
	cover.tagSets = append([]string{""}, strings.Fields(*tags)...)
	return cover, flags.Args(), nil
}

// parsePlatforms reads os/arch pairs separated by spaces.
func parsePlatforms(list string) ([]platform, error) {
	var pairs []platform
	for word := range strings.FieldsSeq(list) {
		goos, goarch, ok := strings.Cut(word, "/")
		if !ok || goos == "" || goarch == "" || strings.Contains(goarch, "/") {
			return nil, fmt.Errorf("%q is not an os/arch pair such as linux/amd64", word)
		}
		pairs = append(pairs, platform{goos: goos, goarch: goarch})
	}
	return pairs, nil
}

// String is the pair as go tool dist list writes it.
func (p platform) String() string {
	return p.goos + "/" + p.goarch
}

// String says what the rows read, as the row's summary prints it.
func (cover lintCoverage) String() string {
	pairs := make([]string, len(cover.platforms))
	for i, pair := range cover.platforms {
		pairs[i] = pair.String()
	}
	sets := "no build tags"
	if len(cover.tagSets) > 1 {
		sets += " and with -tags " + strings.Join(cover.tagSets[1:], ", ")
	}
	return fmt.Sprintf("%s, each with %s", strings.Join(pairs, " "), sets)
}

// buildLabel names one build, as a finding prints it.
func buildLabel(pair platform, tags string) string {
	if tags == "" {
		return pair.String()
	}
	return pair.String() + " with -tags " + tags
}

// coverageFindings refuses a release pair cover does not read, a tracked Go
// file under a directory whose name starts with _, which ./... never matches
// and the set has no use for, and a tracked Go file no build in cover
// compiles. A file under testdata is left to hiddenPackageFindings: ./...
// never reads one, and the build compiles one only when a package imports it.
// A tracked file missing from the work tree passes.
func coverageFindings(root string, tracked []string, cover lintCoverage) ([]string, error) {
	var found []string
	for _, pair := range cover.release {
		if !slices.Contains(cover.platforms, pair) {
			found = append(found, fmt.Sprintf("RELEASE_TARGETS ships %s, which LINT_PLATFORMS does not name, so no lint or vet run reads the code that build compiles. Add it to LINT_PLATFORMS in Taskfile.yml", pair))
		}
	}
	for _, name := range tracked {
		if path.Ext(name) != ".go" {
			continue
		}
		dirs := strings.Split(path.Dir(name), "/")
		if hidden := slices.IndexFunc(dirs, func(dir string) bool { return strings.HasPrefix(dir, "_") }); hidden >= 0 {
			found = append(found, fmt.Sprintf("%q sits under %q, a directory ./... never matches, so vet, lint and test never read it. Move it", name, dirs[hidden]))
			continue
		}
		if slices.Contains(dirs, "testdata") {
			continue
		}
		compiled, err := compiledBy(root, name, cover)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", name, err)
		}
		if !compiled {
			found = append(found, fmt.Sprintf("%q compiles in no build the lint and vet rows read (%s), so no linter reads it. A build constraint or a file name naming another platform or tag does this. Name the pair in LINT_PLATFORMS or the tag set in LINT_TAGS in Taskfile.yml", name, cover))
		}
	}
	return found, nil
}

// compiledBy reports whether any build in cover compiles the tracked Go file
// name, as go's own file matcher decides: by the name's _GOOS and _GOARCH
// suffixes and by its //go:build line. cgo counts as on and as off, since
// the rows read a native pair with the host's setting. The matcher reads a
// name it refuses no further, so the file's presence is checked first.
func compiledBy(root, name string, cover lintCoverage) (bool, error) {
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(name))); err != nil {
		return false, err
	}
	dir := filepath.Join(root, filepath.FromSlash(path.Dir(name)))
	base := path.Base(name)
	for _, pair := range cover.platforms {
		for _, tags := range cover.tagSets {
			for _, cgo := range []bool{false, true} {
				context := build.Context{
					GOOS:        pair.goos,
					GOARCH:      pair.goarch,
					CgoEnabled:  cgo,
					Compiler:    runtime.Compiler,
					BuildTags:   strings.FieldsFunc(tags, func(r rune) bool { return r == ',' }),
					ToolTags:    build.Default.ToolTags,
					ReleaseTags: build.Default.ReleaseTags,
				}
				matched, err := context.MatchFile(dir, base)
				if err != nil {
					return false, err
				}
				if matched {
					return true, nil
				}
			}
		}
	}
	return false, nil
}

// ///////////////////////////////////////////////
// Generated markers
// ///////////////////////////////////////////////

// laxMarkerFindings refuses every tracked Go file under root whose comments
// the package-clause parse collects carry a lax generated marker, unless
// generated names it. It reads them as golangci-lint does: the comments above
// the package clause and those between it and the next token, each trimmed,
// joined and lowercased. A file that does not parse passes, since the build
// fails on it first.
func laxMarkerFindings(root string, tracked, generated []string) ([]string, error) {
	var found []string
	for _, name := range tracked {
		if fold(path.Ext(name)) != fold(".go") || slices.Contains(generated, name) {
			continue
		}
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", name, err)
		}
		file, err := parser.ParseFile(token.NewFileSet(), name, data, parser.PackageClauseOnly|parser.ParseComments)
		if err != nil {
			continue
		}
		var comments []string
		for _, group := range file.Comments {
			comments = append(comments, strings.TrimSpace(group.Text()))
		}
		text := strings.ToLower(strings.Join(comments, "\n"))
		if marker := slices.IndexFunc(laxMarkers, func(marker string) bool { return strings.Contains(text, marker) }); marker >= 0 {
			found = append(found, fmt.Sprintf("%q carries %q in a comment near its package clause, which golangci-lint reads as a generated file's mark and skips the whole file for. Only a file cmd/generate writes may carry one. Reword the comment", name, laxMarkers[marker]))
		}
	}
	return found, nil
}
