package generate

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGeneratedByHeader_Stable(t *testing.T) {
	// Pinning the exact string: changing it is a project-wide break
	// since every generated file carries this line.
	const want = "Auto-generated by cmd/generate. Do not edit."
	assert.Equal(t, want, GeneratedByHeader, "GeneratedByHeader")
}
