package generate

// GeneratedByHeader is the canonical header prepended to every generated
// file, which marks it as the generator's to rewrite. Each format wraps it
// in its own comment syntax: TOML/shell/nginx with '# ', C/Go with '// ',
// JSON Schema via $comment.
const GeneratedByHeader = "Auto-generated by cmd/generate. Do not edit."
