package generate

// GeneratedByHeader is the canonical "do not edit" marker prepended to
// every generated file. Each format wraps it in its own comment syntax:
// TOML/shell/nginx with '# ', C/Go with '// ', JSON Schema via $comment.
const GeneratedByHeader = "Auto-generated by cmd/generate. Do not edit."
